name: Build Artifacts

on:
  push:
    paths:
      - data/**
      - .github/workflows/build.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build-artifacts:
    strategy:
      matrix:
        version: [46]
        build:
          - { type: lhotse-virt, arch: x86_64 }
          - { type: makalu-virt, arch: x86_64 }
          - { type: lhotse-virt, arch: aarch64 }
          - { type: lhotse-rpi4, arch: aarch64 }
          - { type: lhotse-rpi5, arch: aarch64 }
          - { type: makalu-rpi4, arch: aarch64 }
    runs-on: ${{ matrix.build.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6
      - name: "Setup"
        env:
          ARTIFACTS: /artifacts/${{ github.ref_name }}/${{ matrix.version }}/${{ matrix.build.arch }}/teamsbc-${{ matrix.build.type }}/
          UPDATES: /updates/${{ github.ref_name }}/${{ matrix.version }}/${{ matrix.build.arch }}/teamsbc-${{ matrix.build.type }}/
        run: |
          IMAGE_VERSION="${{ matrix.version }}.$(date +%Y%m%d).0"
          sudo mkdir -p "$ARTIFACTS/meta"
          sudo mkdir -p $UPDATES
          echo "ARTIFACTS=$ARTIFACTS" >> $GITHUB_ENV
          echo "UPDATES=$UPDATES" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
      # Workaround: https://github.com/actions/runner-images/issues/14473
      - name: "Fix podman crun resolution"
        run: |
          ( echo '[engine.runtimes]' ; echo 'crun = [ "/usr/local/bin/crun" ]' ) | sudo tee /etc/containers/containers.conf
      - name: "Build"
        run: |
          sudo podman run --rm --privileged \
          -v $ARTIFACTS:/output:Z \
          -v ./data:/data:Z \
          -e IMAGE_BUILDER_EXPERIMENTAL=yamlplus,yamldir=/data/defs,image-id=teamsbc-${{ matrix.build.type }},image-version=$IMAGE_VERSION \
          ghcr.io/osbuild/image-builder:latest \
            --progress=verbose \
            --force-repo-dir=/data/repo \
            build \
            --output-dir /output \
            --distro teamsbc-${{ matrix.version }} \
            --with-manifest \
            ${{ startsWith(matrix.build.type, 'makalu') && '--with-extra partition:pt-usr' || '' }} \
            ${{ matrix.build.type }}
          ls -larth $ARTIFACTS
      - name: "Move extras"
        if: startsWith(matrix.build.type, 'makalu')
        run: |
          sudo mv $ARTIFACTS/*pt-usr*.raw.xz "$UPDATES/teamsbc-${{ matrix.build.type }}-$IMAGE_VERSION.usr.raw.xz"
      - name: "Rename artifact"
        run: |
          sudo mv $ARTIFACTS/*.raw.xz "$ARTIFACTS/teamsbc-${{ matrix.build.type }}-$IMAGE_VERSION.raw.xz"
      - name: "Move metadata"
        run: |
          sudo mv $ARTIFACTS/*.json "$ARTIFACTS/meta/teamsbc-${{ matrix.build.type }}-$IMAGE_VERSION.json"
      - name: "Copy update metadata"
        if: startsWith(matrix.build.type, 'makalu')
        run: |
          sudo mkdir -p "$UPDATES/meta"
          sudo cp -a "$ARTIFACTS/meta/." "$UPDATES/meta/"
      - name: "Generate checksums"
        run: |
          sudo find $ARTIFACTS -type f ! -name '*.sha256' -exec sh -c 'sha256sum "$1" | awk "{print \$1}" > "$1.sha256"' _ {} \;
          sudo find $UPDATES -type f ! -name '*.sha256' -exec sh -c 'sha256sum "$1" | awk "{print \$1}" > "$1.sha256"' _ {} \;
      - name: "Upload"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          aws s3 cp --recursive /artifacts \
            "s3://teamsbc-artifacts/" \
            --no-progress
      - name: "Upload updates"
        if: startsWith(matrix.build.type, 'makalu')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          aws s3 cp --recursive /updates \
            "s3://teamsbc-updates/" \
            --no-progress
