name: Generate Indexes

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Artifacts"]
    types: ["completed"]
    branches:
      - "main"

jobs:
  generate-index:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bucket:
          - teamsbc-artifacts
          - teamsbc-updates
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: "Create"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          go run github.com/teamsbc/s3-directory-listing/cmd/s3-directory-listing@latest create \
            ${{ matrix.bucket }} \
            s3-index-template/default.html \
            -o /tmp/output \
            --sha256sums
      - name: "Sign"
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          gpg --batch --import <<<"$GPG_PRIVATE_KEY"
          find /tmp/output -name SHA256SUMS -exec sh -c '
            gpg --batch --detach-sign -o "$1.sig" "$1"
            gpg --batch --detach-sign --armor -o "$1.asc" "$1"
            cp "$1.sig" "$1.gpg"
          ' _ {} \;
      - name: "Upload"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
        run: |
          aws s3 cp --recursive /tmp/output \
            "s3://${{ matrix.bucket }}/" \
            --no-progress
